PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontA:  <http://tutorial.topbraid.com/ontoA#>

SELECT ?v ?x ?y WHERE 
	{
         ?v a ontA:unEquivanox .
         ?x a ontA:DeuxSubSet1 .
         ?y a ontA:DeuxSubSet2 .
    } 
LIMIT 10